// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env["POSTGRES_PRISMA_URL"] || "postgresql://dummy:dummy@localhost:5432/dummy",
  },
});
