export type ScoreCategory = 
  | 'ATS_READINESS'
  | 'POSITIONING_CLARITY'
  | 'EXECUTIVE_BRANDING'
  | 'VISIBILITY_STRENGTH'
  | 'NETWORKING_MATURITY'
  | 'INTERVIEW_READINESS'
  | 'EMOTIONAL_SUSTAINABILITY'
  | 'HIDDEN_MARKET_READINESS';

export interface ScoreDefinition {
  category: ScoreCategory;
  name: string;
  description: string;
  weight: number;
}

export const SCORE_FRAMEWORK: Record<ScoreCategory, ScoreDefinition> = {
  ATS_READINESS: {
    category: 'ATS_READINESS',
    name: 'ATS Readiness',
    description: 'Measures how well the resume is optimized for Applicant Tracking Systems and keyword parsing.',
    weight: 0.15
  },
  POSITIONING_CLARITY: {
    category: 'POSITIONING_CLARITY',
    name: 'Positioning Clarity',
    description: 'Measures the sharpness of the value proposition and market fit.',
    weight: 0.20
  },
  EXECUTIVE_BRANDING: {
    category: 'EXECUTIVE_BRANDING',
    name: 'Executive Branding',
    description: 'Measures the quality and consistency of digital presence and professional narrative.',
    weight: 0.15
  },
  VISIBILITY_STRENGTH: {
    category: 'VISIBILITY_STRENGTH',
    name: 'Visibility Strength',
    description: 'Measures how likely the candidate is to be found by headhunters and recruiters.',
    weight: 0.10
  },
  NETWORKING_MATURITY: {
    category: 'NETWORKING_MATURITY',
    name: 'Networking Maturity',
    description: 'Measures the effectiveness of the candidates outreach and relationship-building strategy.',
    weight: 0.10
  },
  INTERVIEW_READINESS: {
    category: 'INTERVIEW_READINESS',
    name: 'Interview Readiness',
    description: 'Measures the preparation for high-stakes technical and behavioral interviews.',
    weight: 0.10
  },
  EMOTIONAL_SUSTAINABILITY: {
    category: 'EMOTIONAL_SUSTAINABILITY',
    name: 'Emotional Sustainability',
    description: 'Measures psychological resilience, burnout risk, and execution mindset.',
    weight: 0.10
  },
  HIDDEN_MARKET_READINESS: {
    category: 'HIDDEN_MARKET_READINESS',
    name: 'Hidden Market Readiness',
    description: 'Measures the capability to tap into unposted job opportunities.',
    weight: 0.10
  }
};

export class ScoringEngine {
  static calculateGlobalScore(scores: Record<ScoreCategory, number>): number {
    let totalScore = 0;
    let totalWeight = 0;

    for (const category in SCORE_FRAMEWORK) {
      const cat = category as ScoreCategory;
      const value = scores[cat] || 0;
      totalScore += value * SCORE_FRAMEWORK[cat].weight;
      totalWeight += SCORE_FRAMEWORK[cat].weight;
    }

    return Math.round(totalScore / totalWeight);
  }

  static getJustification(category: ScoreCategory, score: number): string {
    // In a real implementation, this would be generated by AI or based on logic rules
    if (score > 80) return "Executive level performance. Minimal refinement needed.";
    if (score > 60) return "Professional standard. Specific strategic gaps identified.";
    if (score > 40) return "Operational but weak. Requires significant structural overhaul.";
    return "Critical failure. Fundamental positioning needs to be rebuilt.";
  }
}
